### ISSUE TITLE
Shift key doesn't function correctly

### ISSUE THREAD

**Issue by chenha0** [thefloweringash/iousbhiddriver-descriptor-override#18]
I'm using a noppoo choc mid with Yosemite. My problem here is I can't type characters of `~_+{}|:"<>?` with shift key, while `shift + other keys` works perfectly.

Any ideas?

**Comment by dawncold** [comment]
@chenha0 I installed the Karabiner, the link in here http://thefloweringash.github.io/iousbhiddriver-descriptor-override/

I opened Karabiner, shift key works fine, closed it, shift key works bad.

**Comment by thefloweringash** [comment]
This "globalised modifier" behaviour is not part of this project, since Karabiner handles that. If installing Karabiner didn't fix this issue please reopen.
