### ISSUE TITLE
Choc Pro (made in China) not working

### ISSUE THREAD

**Issue by maddie** [thefloweringash/iousbhiddriver-descriptor-override#19]
It seems it's not listed as supported in Info.plist

These are info:

![screen shot 2015-01-29 at 11 30 10](https://cloud.githubusercontent.com/assets/221872/5952001/3a605668-a7aa-11e4-80c6-d06e4c322b6c.png)

Is it possible to support it?

**Comment by maddie** [comment]
Now works after using `rake scan` and compile install manually.

But is there a way of getting the keyboard recognized without unplug then plugging in the keyboard again?

**Comment by thefloweringash** [comment]
You should only have to unplug and plug in if the keyboard was inserted before the kext, which normally happens only immediately after installation. If this is not the case, please reopen.
