### ISSUE TITLE
Doesn’t work on El Capitan

### ISSUE THREAD

**Issue by paulopaniago** [thefloweringash/iousbhiddriver-descriptor-override#23]
I tested with two MacBooks - white and pro - with and without Plover (an open source stenography program). The Noppoo Choc is one of the few gaming keyboards that can emulate a Steno Machine through usb – VERY IMPORTANT DRIVER

**Comment by paulopaniago** [comment]
I forgot to mention that it was working fine on both MacBooks with Yosemite.

**Comment by thefloweringash** [comment]
I'm working on updates for El Capitan, and tracking the issue as #22.
