### ISSUE TITLE
El Capitan issues with unsigned driver?

### ISSUE THREAD

**Issue by cbreault** [thefloweringash/iousbhiddriver-descriptor-override#24]
My noppoo stopped working with the upgrade and it's been really frustrating not being able to use it with my setup at work. Can anyone shine some light on this issue?

✘  /System/Library/Extensions  sudo kextutil -v /System/Library/Extensions/IOUSBHIDDriverDescriptorOverride.kext
Defaulting to kernel file '/System/Library/Kernels/kernel'
Diagnostics for /System/Library/Extensions/IOUSBHIDDriverDescriptorOverride.kext:
Code Signing Failure: not code signed
/System/Library/Extensions/IOUSBHIDDriverDescriptorOverride.kext appears to be loadable (not including linkage for on-disk libraries).
Untrusted kexts are not allowed
ERROR: invalid signature for ryangoulden.driver.IOUSBHIDDriverDescriptorOverride, will not load

**Comment by thefloweringash** [comment]
I'm working on updates for El Capitan, and tracking the issue as #22.
