### ISSUE TITLE
Support for Poseidon ZX Illuminated - can't get Cmd key to work.

### ISSUE THREAD

**Issue by GrubLord** [thefloweringash/iousbhiddriver-descriptor-override#37]
Hi there,

Thank you for your excellent project - it's helped me get the Poseidon ZX Illuminated keyboard *almost* functional. The only remaining issue is that the command-key doesn't work, which sadly I haven't been able to find a fix for (my workaround at the moment has been to switch it with the less-useful Option/Alt key in the Keyboard control panel).

Here's my generated yaml file for the keyboard:
https://cloudstor.aarnet.edu.au/plus/index.php/s/hMgmFDmvikwmY0Y

Could I get your help with the final step of making that final button work?

**Comment by thefloweringash** [comment]
Hello,

In these cases we need to see what the raw reports from the keyboard look like when sending the command key. There's a [hid_report_dumper][] directory with a simple, but unpolished, utility to do so.

[hid_report_dumper]: https://github.com/thefloweringash/iousbhiddriver-descriptor-override/tree/master/hid_report_dumper

**Comment by GrubLord** [comment]
Thanks kindly for getting back to me - sadly, I wasn't able to get your utility to print out anything much except "Seized 0 devices (3 failed)".

**Comment by thefloweringash** [comment]
Taking over the raw keyboard devices requires root privileges, which is one way it might fail to seize the devices. Did you run with `sudo`?

**Comment by GrubLord** [comment]
No, I hadn't, and doing this actually helped me to resolve the problem myself: turns out there is a button on the keyboard which doesn't seem to do anything, but its effect is to make the Windows key register as Ctrl instead... for some reason. I guess to prevent it booting you out of a game.

So actually using the yaml file from above, along with your code as-is, works fine, as long as that key is kept appropriately toggled.

Thanks again for your project. It's been really helpful!
