### ISSUE TITLE
Cannot download

### ISSUE THREAD

**Issue by leftstick** [thefloweringash/iousbhiddriver-descriptor-override#38]
The download address is invalid: http://thefloweringash.com/iousbhiddriver-descriptor-override/downloads/IOUSBHIDDriverDescriptorOverride-2013-04-21-b545d15.pkg

![screen shot 2018-01-11 at 10 49 44 am](https://user-images.githubusercontent.com/1059956/34806344-62fa5e9c-f6bd-11e7-8731-4da5d9f498ee.png)

**Comment by thefloweringash** [comment]
Fixed. Sorry about the delay.
