### ISSUE TITLE
Incompatible with 10.15.1

### ISSUE THREAD

**Issue by le4ker** [thefloweringash/iousbhiddriver-descriptor-override#41]
First of all thank you so much for working on this 😄 

Second, on macos 10.15.1 I'm getting a 

```
The package is trying to install content to the system volume. Contact the software manufacturer for assistance.
```

**Comment by skoonppman** [comment]
I meet the same question

**Comment by andrewginns** [comment]
Looks like this problem is caused by SIP in Catalina. Method to disable it here https://support.studionetworksolutions.com/hc/en-us/articles/115003839246-How-to-disable-Systems-Integrity-Protection-SIP-in-macOS

**Comment by murmurlid** [comment]
> Looks like this problem is caused by SIP in Catalina. Method to disable it here https://support.studionetworksolutions.com/hc/en-us/articles/115003839246-How-to-disable-Systems-Integrity-Protection-SIP-in-macOS

I closed SIP, but it still can't work , "Incompatible" with my mac pro 10.15.3
